// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: grpc/protos/whatsapp.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WhatsappClient is the client API for Whatsapp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WhatsappClient interface {
	InsertWozMessage(ctx context.Context, in *InsertWozMessageRequest, opts ...grpc.CallOption) (*WhatsappMessageResponse, error)
}

type whatsappClient struct {
	cc grpc.ClientConnInterface
}

func NewWhatsappClient(cc grpc.ClientConnInterface) WhatsappClient {
	return &whatsappClient{cc}
}

func (c *whatsappClient) InsertWozMessage(ctx context.Context, in *InsertWozMessageRequest, opts ...grpc.CallOption) (*WhatsappMessageResponse, error) {
	out := new(WhatsappMessageResponse)
	err := c.cc.Invoke(ctx, "/protos.Whatsapp/InsertWozMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WhatsappServer is the server API for Whatsapp service.
// All implementations must embed UnimplementedWhatsappServer
// for forward compatibility
type WhatsappServer interface {
	InsertWozMessage(context.Context, *InsertWozMessageRequest) (*WhatsappMessageResponse, error)
	mustEmbedUnimplementedWhatsappServer()
}

// UnimplementedWhatsappServer must be embedded to have forward compatible implementations.
type UnimplementedWhatsappServer struct {
}

func (UnimplementedWhatsappServer) InsertWozMessage(context.Context, *InsertWozMessageRequest) (*WhatsappMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertWozMessage not implemented")
}
func (UnimplementedWhatsappServer) mustEmbedUnimplementedWhatsappServer() {}

// UnsafeWhatsappServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WhatsappServer will
// result in compilation errors.
type UnsafeWhatsappServer interface {
	mustEmbedUnimplementedWhatsappServer()
}

func RegisterWhatsappServer(s grpc.ServiceRegistrar, srv WhatsappServer) {
	s.RegisterService(&Whatsapp_ServiceDesc, srv)
}

func _Whatsapp_InsertWozMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertWozMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhatsappServer).InsertWozMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Whatsapp/InsertWozMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhatsappServer).InsertWozMessage(ctx, req.(*InsertWozMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Whatsapp_ServiceDesc is the grpc.ServiceDesc for Whatsapp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Whatsapp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Whatsapp",
	HandlerType: (*WhatsappServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertWozMessage",
			Handler:    _Whatsapp_InsertWozMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/protos/whatsapp.proto",
}
