// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: grpc/protos/whatsapp.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertWozMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InsertWozMessageRequest) Reset() {
	*x = InsertWozMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_whatsapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertWozMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertWozMessageRequest) ProtoMessage() {}

func (x *InsertWozMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_whatsapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertWozMessageRequest.ProtoReflect.Descriptor instead.
func (*InsertWozMessageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_protos_whatsapp_proto_rawDescGZIP(), []int{0}
}

func (x *InsertWozMessageRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *InsertWozMessageRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *InsertWozMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WhatsappMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From      string               `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To        string               `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Timestamp string               `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type      string               `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	TextId    *string              `protobuf:"bytes,6,opt,name=textId,proto3,oneof" json:"textId,omitempty"`
	Text      *WhatsappMessageText `protobuf:"bytes,7,opt,name=text,proto3,oneof" json:"text,omitempty"`
}

func (x *WhatsappMessageResponse) Reset() {
	*x = WhatsappMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_whatsapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhatsappMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsappMessageResponse) ProtoMessage() {}

func (x *WhatsappMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_whatsapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsappMessageResponse.ProtoReflect.Descriptor instead.
func (*WhatsappMessageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_protos_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *WhatsappMessageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhatsappMessageResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *WhatsappMessageResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *WhatsappMessageResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WhatsappMessageResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WhatsappMessageResponse) GetTextId() string {
	if x != nil && x.TextId != nil {
		return *x.TextId
	}
	return ""
}

func (x *WhatsappMessageResponse) GetText() *WhatsappMessageText {
	if x != nil {
		return x.Text
	}
	return nil
}

type WhatsappMessageText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *WhatsappMessageText) Reset() {
	*x = WhatsappMessageText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_protos_whatsapp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhatsappMessageText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsappMessageText) ProtoMessage() {}

func (x *WhatsappMessageText) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_protos_whatsapp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsappMessageText.ProtoReflect.Descriptor instead.
func (*WhatsappMessageText) Descriptor() ([]byte, []int) {
	return file_grpc_protos_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *WhatsappMessageText) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhatsappMessageText) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_grpc_protos_whatsapp_proto protoreflect.FileDescriptor

var file_grpc_protos_whatsapp_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x68,
	0x61, 0x74, 0x73, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0x57, 0x0a, 0x17, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x6f,
	0x7a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xe6, 0x01,
	0x0a, 0x17, 0x57, 0x68, 0x61, 0x74, 0x73, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x06, 0x74, 0x65, 0x78, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x06, 0x74, 0x65, 0x78, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x34, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x57, 0x68, 0x61, 0x74, 0x73, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x48, 0x01, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x49, 0x64, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x22, 0x39, 0x0a, 0x13, 0x57, 0x68, 0x61, 0x74, 0x73, 0x61,
	0x70, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x32, 0x62, 0x0a, 0x08, 0x57, 0x68, 0x61, 0x74, 0x73, 0x61, 0x70, 0x70, 0x12, 0x56, 0x0a,
	0x10, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x57, 0x6f, 0x7a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x57, 0x6f, 0x7a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x57, 0x68, 0x61, 0x74,
	0x73, 0x61, 0x70, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x69, 0x6e,
	0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_protos_whatsapp_proto_rawDescOnce sync.Once
	file_grpc_protos_whatsapp_proto_rawDescData = file_grpc_protos_whatsapp_proto_rawDesc
)

func file_grpc_protos_whatsapp_proto_rawDescGZIP() []byte {
	file_grpc_protos_whatsapp_proto_rawDescOnce.Do(func() {
		file_grpc_protos_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_protos_whatsapp_proto_rawDescData)
	})
	return file_grpc_protos_whatsapp_proto_rawDescData
}

var file_grpc_protos_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_protos_whatsapp_proto_goTypes = []interface{}{
	(*InsertWozMessageRequest)(nil), // 0: protos.InsertWozMessageRequest
	(*WhatsappMessageResponse)(nil), // 1: protos.WhatsappMessageResponse
	(*WhatsappMessageText)(nil),     // 2: protos.WhatsappMessageText
}
var file_grpc_protos_whatsapp_proto_depIdxs = []int32{
	2, // 0: protos.WhatsappMessageResponse.text:type_name -> protos.WhatsappMessageText
	0, // 1: protos.Whatsapp.InsertWozMessage:input_type -> protos.InsertWozMessageRequest
	1, // 2: protos.Whatsapp.InsertWozMessage:output_type -> protos.WhatsappMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_protos_whatsapp_proto_init() }
func file_grpc_protos_whatsapp_proto_init() {
	if File_grpc_protos_whatsapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_protos_whatsapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertWozMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_whatsapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhatsappMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_protos_whatsapp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhatsappMessageText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_protos_whatsapp_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_protos_whatsapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_protos_whatsapp_proto_goTypes,
		DependencyIndexes: file_grpc_protos_whatsapp_proto_depIdxs,
		MessageInfos:      file_grpc_protos_whatsapp_proto_msgTypes,
	}.Build()
	File_grpc_protos_whatsapp_proto = out.File
	file_grpc_protos_whatsapp_proto_rawDesc = nil
	file_grpc_protos_whatsapp_proto_goTypes = nil
	file_grpc_protos_whatsapp_proto_depIdxs = nil
}
